name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test HTML
        run: |
          grep -q "CI/CD Lab" index.html

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository }}:latest

      - name: Deploy container
        shell: pwsh
        run: |
          docker rm -f cicd-cd 2>$null
          docker run -d --name cicd-cd -p 8086:80 ghcr.io/${{ github.repository }}:latest
